### ISSUE TITLE
FEMP / FEServer counts every Phase as a Turn

### ISSUE THREAD

**Issue by ghost** [eliatlarge/FEMultiPlayer-V2#103]
Issue type: `problem`
#### Description:

This has been bothering me for some time now but I keep forgetting to report it. Currently FEMP considers every Phase to be it's own Turn when in the original games, a Turn consists of two Phases (_under normal circumstances - let's not get into non-standard scenarios such as multiple players on each team_). Turn Count should only advance after the last / 2nd Phase has been completed.

---
#### Actual Behavior:

Turn Count advances with each and every Phase.
#### Expected Behavior:

Turn Count should only advance after all players have completed their respective Phase for that Turn. Advancing after the last Phase of each Turn.

**Comment by BChezza** [comment]
I don't really find it a problem. I understand ocd and all, but I think its ok overall.

**Comment by SapphireTactician** [comment]
You fail to understand that it's a problem the moment things like stat changes, or rules / features like a turn limit are implemented.

**Comment by SapphireTactician** [comment]
Closing as `Fixed` as per #157 . Good job.
