### ISSUE TITLE
Sudden Death Modifier only reduces current HP to 1, not Max HP

### ISSUE THREAD

**Issue by SapphireTactician** [eliatlarge/FEMultiPlayer-V2#104]
Issue type: `problem`

####  Description:

The "Sudden Death" Modifier only reduces the unit's current HP to 1, not their maximum HP - rendering the entire mode pointless if one brings healing items / staves.

-------

#### Actual Behavior

Current HP is reduced to 1 for all units.

#### Expected Behavior

Maximum HP is reduced to 1 for all units.

**Comment by Purplemandown** [comment]
This has been fixed, and will be in a pull request later today.  (Can't assign myself to it.)

**Comment by eliatlarge** [comment]
@Purplemandown wtf it wont let me assign you either

**Comment by SapphireTactician** [comment]
We probably shouldn't close bugs addressed by a Pull Request until I conclude my tests on them... but ok. Sorry I'm behind schedule, life happened.

**Comment by eliatlarge** [comment]
no im sorry I don't remember closing this?

**Comment by SapphireTactician** [comment]
Now that's merged and addresses the issue, we can close it. Closing as `Fixed` via #106
