### ISSUE TITLE
Village Terrain gives the wrong / balance breaking buff

### ISSUE THREAD

**Issue by SapphireTactician** [eliatlarge/FEMultiPlayer-V2#105]
Issue type: `problem`

#### Description:

This became clearly apparent in my games with **Pwntagonist**, when forced to turtle, I tucked Gradivus Oswin away in the Village (*which for reasons completely unbeknowst to me offers +10 DEF instead of +10 AVO*) rendering him literally invincible to physical attacks with 45 DEF when it was all said and done.

-------

#### Examples:

![2016-06-09--201552_1600x900](https://cloud.githubusercontent.com/assets/18563664/15950683/12d8104c-2e7f-11e6-9d02-be9a5bf2a950.png)
*As per the original FE games, it's `+10 Avo` NOT `+10 Def`, you done goofed @eliatlarge*

-------

#### Actual Behavior:

Village gives a +10 boost to DEF

#### Expected Behavior:

Village gives a +10 boost to AVO.

#### Suggested Behavior:

I think Village should give +1 DEF / RES, +10 AVO, and +5 HP

**Comment by BChezza** [comment]
+5 hp feels a bit much. +3 feels a bit better, its a sort of standard number.
We could also give a hit bonus.

**Comment by SapphireTactician** [comment]
Oh hi. :) I feel 3 would be insignificant though. 5 would possibly buy a unit an extra round of battle.

I don't see a hit bonus being logical at all, how would a village help you hit better. Def and Avo could be explained by the unit having cover. HP can be explained by the villagers offering minor first aid to the unit.

**Comment by BChezza** [comment]
I guess, but the villagers could rally you on?

**Comment by BChezza** [comment]
We have to keep it so its somewhat tactical, a balance of not rushing to get to it, but not something which is rather useless and does not really affect battle outcome. I think maybe 5 is better.

**Comment by Purplemandown** [comment]
This'll be in my next pr (restoring it to intended value), later today.  I can't seem to assign myself to things.  (Probably just an Eli thing again)

**Comment by eliatlarge** [comment]
@Purplemandown yeah honestly idk. it's not giving any option other than me for some reason.

**Comment by SapphireTactician** [comment]
Closing as `Fixed` via #106
