### ISSUE TITLE
weapons.txt and stats.txt are not true .tsv files due to filler spaces between tabs

### ISSUE THREAD

**Issue by SapphireTactician** [eliatlarge/FEMultiPlayer-V2#120]
Issue type: `problem`

#### Description:

Trying to load quasi-tsv'd files such as `weapons.txt` and `stats.txt` into an application meant for editing such files, such as Open / Libre Office Calc, or Microsoft Excel, results in the file being an incomprehensible mess to such editors because for reasons completely beyond my comprehension, someone thought it was okay to buffer the tabs with spaces.

Lets make these files truly .tsv files by removing unnecessary spaces (*I don't even wanna know how the game actually parses around that mess*) so I actually don't get a migraine when editing and experimenting with them.

**Comment by eliatlarge** [comment]
It's surprisingly simple, it simply split()s whitespace with regex \s+. I'll upload my fix in a minute.
