### ISSUE TITLE
Multiple combat triggers activating simultaniously produces unexpected results

### ISSUE THREAD

**Issue by rayrobdod** [eliatlarge/FEMultiPlayer-V2#124]
Issue type: `problem`
#### Description:

If Colossus activates while the unit is using a crossbow, then the attack's damage is `(weapon might) - (opponent defense) - (attacker strength)`, whereas it is expected to be `(weapon might) - (opponent defense)` (or possibly Colossus should not activate at all)

---
#### Examples:
- Tournament #3 match 1 (https://www.twitch.tv/falseproof/v/74319943?t=58m15s timestamp 00:58:15)
- ![github_issue](https://cloud.githubusercontent.com/assets/11641215/16431523/067f1b9a-3d4f-11e6-9f4a-dbf1e8fc540f.png)
  (note "No Damage" with preview predicting 14 and colossus-indicating-thunderbolt)

**Comment by rayrobdod** [comment]
What I think is happening:

0. Before the triggers are activated, str is `A`
1. Colossus adds a modifier to double str: `str: +A`; "str" is `A + A`
2. Crossbow adds a modifier to reduce str to zero: `str: -\(A + A\)`
  * However, the crossbow modifier *overrides* the colossus modifier instead of appending to it: str is `A + -(A + A)` instead of `A + A + -(A + A)`
3. After triggers are activated, str is `-A`
4. battle damage is `weapon.might + attacker.str - defender.def`, where str is `-A`.

I believe at this time that Crossbow/Colossus and the Gamble/Deadeye pair are the only pair of combat triggers that aren't mutually exclusive and modify to the same stat, but since personal skills activate before class skills, the Gamble/Deadeye pair produces expected results.

**Comment by SapphireTactician** [comment]
I can't see anything on if Colossus can active with a Crossbow or not. What we do know is that it modifies STR, but Crossbows ignore STR. That being said, instead of Crossbow's modifying STR as you pointed out, can't they just use their own damage formula of `(Weapon MT) - (Target's Def)`?
