### ISSUE TITLE
Throne doesn't yield correct RES bonus

### ISSUE THREAD

**Issue by ghost** [eliatlarge/FEMultiPlayer-V2#127]
Issue type: `problem`
#### Description:

Since we're mirroring the behavior of the GBA FE games (_primarily_), it is important to note that the `THRONE` terrain is suppose to yield `+5 RES` in addition to `+3 DEF, +30 AVO, and +10% HP`. Currently, it does not, only offering `+3 DEF & RES, +30 AVO, and +10% HP`

While making this change, I propose we also separate DEF and RES into separate categories for the terrain bonuses so that new terrains like Wardwood can become possible if we like.

---
#### Reference(_s_):

| **Terrain** | **Def** | **Avoid** | **Heal** | **Move Cost** | **Other Data** |
| :-: | :-: | :-: | :-: | :-: | :-: |
| Throne | 3 | 30 | 10% | 1 | Restores conditions. Resistance +5 |

http://fireemblem.wikia.com/wiki/Throne
http://fireemblem.wikia.com/wiki/Terrain

**Comment by SapphireTactician** [comment]
@rayrobdod Tested and confirmed. Can you make a pull request so we can get this fix in there?

**Comment by SapphireTactician** [comment]
Closing as `Fixed` as per #133
