### ISSUE TITLE
Inspect Button for "Help" / "Info" dialogue

### ISSUE THREAD

**Issue by ghost** [eliatlarge/FEMultiPlayer-V2#129]
Issue type: `feature request`
#### Description:

Currently, outside of memorization, there is no way of knowing what an enemy unit capable of. While we can view an enemy's stats, we can't view their weapon stats to see the full picture. In the original games, one had to go to separate screen, then press the R button for an "Info" / "Help" dialogue to appear which displayed weapon stats.

Players should be able to do that directly from the Map without the need for a new screen. When the cursor is over a unit, the player should be able to press the a button that's the equivalent to the R button on the GBA.

This feature was [requested by our current champion](https://www.reddit.com/r/FEMP/comments/4ues4j/player_feedback/d5vv1o7), and I feel it's worth adding.

---
#### Examples:

![2-b1p3](https://cloud.githubusercontent.com/assets/18563664/17263082/05115842-55ad-11e6-8710-370b485dc721.png)

**Comment by SapphireTactician** [comment]
Closing as `fixed` as per #151 . Thank you. :)
