### ISSUE TITLE
Item Menu should display Weapon Stats

### ISSUE THREAD

**Issue by ghost** [eliatlarge/FEMultiPlayer-V2#130]
Issue type: `feature request`
#### Description:

Related to #129 , when a player manages their Inventory, they should be able to see their weapons stats and / or how it affects their current stats while the cursor is over it.

---
#### Examples:

Granted in this picture it's showing how it affects their stats overall, and not just the weapon's, but either is acceptable.

![391718-fire-emblem-path-of-radiance-gamecube-screenshot-the-items](https://cloud.githubusercontent.com/assets/18563664/17263337/85882982-55ae-11e6-9cbb-ede422f3094a.jpg)

**Comment by eliatlarge** [comment]
Thanks for this last contribution!

On saturday the 27th, We plan to have a meeting on the direction of FEMP, potentially to create a new project with new assets and features. While you might not see this in time, you can contact me any time on the discord or at eliatlarge@gmail.com . Hope to see you!

**Comment by SapphireTactician** [comment]
Closing as `Fixed` as per #151 . Good job.
