### ISSUE TITLE
If a unit activates multiple skills at once, only one is displayed

### ISSUE THREAD

**Issue by SapphireTactician** [eliatlarge/FEMultiPlayer-V2#145]
Issue type: `problem`
#### Description:

If a single unit activates multiple skills activate at once, only one is displayed (*seems like the one that activates last*).

---
#### Examples:

Use the Vegas modifier. `Gamble` will not display if another skill such as `Sol` activates even though it is still applied.

**Comment by wellme** [comment]
Fixed on [wellme:bug-fixing](https://github.com/wellme/FEMultiPlayer-V2/tree/bug-fixing)
![image](https://user-images.githubusercontent.com/7041069/34322832-86d7995e-e800-11e7-8fed-45493cfc258c.png)
