### ISSUE TITLE
Camera location updates during FoW Enemy Phase

### ISSUE THREAD

**Issue by SapphireTactician** [eliatlarge/FEMultiPlayer-V2#155]
Issue type: `problem`

#### Description:

This is a case of a good feature from normal play coming back to bite us. Should be easy to address, I hope. Normally, the map camera updates during the Enemy Phase each time the opponent moves a unit or takes an action so that the player knows what they're opponent just did. However, this compromises the effectiveness of the fog as it hints to the player's location / direction on larger maps.

The camera should only follow the opponent if the opponent moves a unit or performs an action within the player's collective field of vision.

*Edit: Feel free to disregard if this is already addressed in the PR, I'll check that out hopefully tomorrow.*

-------

#### Examples:

Play on a map such as Delphino, Move unit, wait / act, watch from opponent's client.

**Comment by wellme** [comment]
Fixed
