### ISSUE TITLE
Dropped rescued enemies are shown grayed out

### ISSUE THREAD

**Issue by wellme** [eliatlarge/FEMultiPlayer-V2#176]
**Issue type:** `problem`

### Description:

Title. This can lead to confusion: the player sees the enemy grayed out, which typically implies that it's one of their unit that has already done they're move. They think it's one of theirs, but it's actually an enemy.

**Comment by rayrobdod** [comment]
Do you mean "units that were dropped on enemy phase because their rescuer died" or something else?
