### ISSUE TITLE
Give druids specialization

### ISSUE THREAD

**Issue by eliatlarge** [eliatlarge/FEMultiPlayer-V2#2]
*Canas* - specializes in HP, Magic, and Resistance
    *Ewan* - specializes in Skill, Speed, and Luck
    *Knoll* - specializes in HP, Defense, and Constitution (if we get that weapon weight system)

Keep in mind that when I say "specialize", I don't mean anything higher than 23 (besides HP). The trade-off with Druids is that they have mediocre stats in exchange for niche weaponry.

**Comment by SapphireTactician** [comment]
The Druid's specialty, overall as a class, is suppose higher HP and Def than other magic classes, along with the fact that their weapons have the highest Mt of all the tome wielding classes in comparison to other tomes of the same weapon rank. They're essentially the "Warriors" of the magic classes.

**Comment by eliatlarge** [comment]
lol this is from way early on, I prolly should remove it because we've already balanced them
