### ISSUE TITLE
Console Canto for Paladins

### ISSUE THREAD

**Issue by eliatlarge** [eliatlarge/FEMultiPlayer-V2#3]
Give Paladins Console Canto, the ability to use up your remaining movement after attacking. This would give Paladins the ability to hit-and-run, picking at enemy lines while still attempting to maintain a defensive position.

**Comment by SapphireTactician** [comment]
More importantly, for all mounted and flying classes, let's not forget that Re-Move (*the earlier version of Canto*) was always a thing - allowing the player to use up the remainder of their movement after rescuing (*which lends even more to hit-and-run tactics, especially if the player is smart enough to set up a relay network of mounts - a tactic I employ a lot on each FE installment's hardest difficulty*), giving / taking, and trading (*important when considering they can pass along or borrow a better suited weapon then wait with it equipped*).

**Comment by SapphireTactician** [comment]
Just to confirm, by closing this with the wording of Console Canto, this means they can also access the remainder of their movement after Rescuing, Giving, Taking, and Trading as well, and not just after combat / staff use, right?

**Comment by eliatlarge** [comment]
I closed it so I can focus on the other canto thread. I'll make sure it works for all options, when I get the chance to implement it.
