### ISSUE TITLE
Anyone can Rescue Anyone without regard for what would be Rescued Unit's Weight / Con

### ISSUE THREAD

**Issue by SapphireTactician** [eliatlarge/FEMultiPlayer-V2#41]
Issue type: `problem`

#### Description:

Currently, any unit can rescue another unit as weight / Constitution, and Aid haven't been implemented. This results in such curious scenarios as Matthew being able to rescue Oswin. Yes, I attempted this, and yes, the game let me. This applies to Giving and Taking as well.

I've been told that implementing Con and Aid stats, which would fix this, would involve tons of coding, so for the time being, a temporary / sloppy workaround would be to specifically list which units CAN'T be rescued by the rescuing unit.

EDIT: Changed title for clarification. Fixed typos

**Comment by eliatlarge** [comment]
closed by commit 0da79e9

**Comment by eliatlarge** [comment]
ok, I'll do this the democracy way because I've never actually played the gba games

**Comment by SapphireTactician** [comment]
I probably should've explained better that rescuing is based on weight and aide, the problem is we lack those stats.

##### As a workaround, we at least know the average weight and aide of each class, and with this we can make a list of what classes can rescue who. Keep in mind that the following is a very sloppy, "quick and dirty" workaround / solution.

* Lords, Generals, and all horse / pegasi / wyvern mounts can rescue anyone due to their superior aide.
* Pegasi and Troubadours / Valkyries are a weird exception who can rescue anyone, AND be rescued by anyone due to low Con.
* Berserkers and Warriors can rescue anyone equal to or below them on this list
* Heroes and Druids / Sorcerers can rescue anyone equal to or below them on this list
* Swordmasters and Assassins can rescue anyone equal to or below them on this list
* Sages (*and Bishops once added*) can rescue anyone equal to or below them on this list
* Falconknights and Troubadours / Valkyries are the lightest and thus can be rescued by anyone, as well as rescue anyone due to the strength of their mounts.

*Again, I'll stress that this is a "quick and dirty" fix that opts to make rescuing restrictions based on class instead of Con and Aide, by taking into consideration on average what units could rescue who in the official games without implementing the needed stats*

**Comment by eliatlarge** [comment]
This is good. When I get the time, I'll think up a con system. for now a tier thing can work.

**Comment by SapphireTactician** [comment]
Are tiers for rescuing set up for now until the Con system is ready? Or better yet, is Con system rescuing already ready since Shoving / Smiting (*which is also Con based*) was added?

**Comment by eliatlarge** [comment]
closed by 5db0bb0.

all lord horse units recieved a +10 to con, to account for rescuing.

**Comment by SapphireTactician** [comment]
That wouldn't always be the case, some are light enough to be rescued anyways. Like Florina's Con is 4, she's the lightest in perhaps the entire series. Eliwood's Con as Knight Lord is 9 btw

**Comment by eliatlarge** [comment]
then I should ignore con for mounted units?

**Comment by SapphireTactician** [comment]
Nah, cause most mounts are very heavy, such as your Paladins. It's really based on the unit, but some lords like Eliwood, and Falconknights are exceptions to the rule cause they have low Con but high Aide. Without an actual Aide stat, we're doing jury-rig by assuming the maximum Con of a unit someone can rescue is one less than their own Con.

**Comment by eliatlarge** [comment]
can you specifically write out the rules to this one then?

**Comment by eliatlarge** [comment]
btw, I uploaded a broken commit by accident, so moving any horse units will probably trigger a crash

**Comment by SapphireTactician** [comment]
Without an Aide stat, it gets a bit messy for certain units. The best solution would be to an Aide stat, then I'd just tell you the formula for calculating everyone's Aide. Because the way it's meant to work is that anyone whose Con is less than the rescuer's Aide stat, can be rescued. Likewise, you can't Give to a unit whose Aide is not greater than the Con of the person you're giving. Furthermore, you can't Take a unit from another unit if your Aide isn't greater than the Con of the unit you're trying to Take.

The formula for Aide is as follows:
* All foot units: `Con - 1`
* All male mounts and male fliers: `25 - Con`
* All female mounts and female fliers: `20 - Con`

**Comment by SapphireTactician** [comment]
Some of your Con values are off, provided are the corrected Con values for the units with incorrect Con.

Matthew: 7

Dart: 13
Ross: 13

Amelia: 11
Gilliam: 16
Wallace: 15
Oswin: 16

Gerik: 15

Eirika: 7
Eliwood: 9
Ephraim: 10
Hector: 15
Roy: 8
Marth: *The Con stat didn't exist in Marth's games, we can't leave it at 0, so we'll say* 6
Ike: 13 (*as per Radiant Dawn's Weight stat*)

Kent: 11
Forde: 11 (*It looks like you're using Great Knight con instead of Paladin for these. Provided are Paladin Con*)
Franz: 11
Sain: 11
Kyle: 12

Ewan: 7
Knoll: 8 (*someone really screwed up these two*)

Bartre: 15  
  
After that's fixed, we can close this since it's working fine now otherwise.

**Comment by SapphireTactician** [comment]
Closing as "Fixed" as per ef8aac58e448a3366a0c5e651af8f27850d1c1a4 and 0deb6b086bef454a4af410d276d19a057ce25537

Thank you @eliatlarge :-D

**Comment by eliatlarge** [comment]
and with that, the saga ends. wew lad
