### ISSUE TITLE
Horseslayer / Longsword / Halberd / etc. get "effective" bonus against Pegasi

### ISSUE THREAD

**Issue by SapphireTactician** [eliatlarge/FEMultiPlayer-V2#43]
Issue type: `problem`

#### Description:

Anti-cavalry weapons such as the Horseslayer, Longsword, and Halberd get a bonus against Falconknights - Pegasi / flying units. This was never the case in any FE game as even their item help descriptions often say, "Effective against cavalry", which are not pegasi. A notable exception are Awakening and Fates which indiscriminately counts calvary, and pegasi, as "beasts" along with griffons and Taguel, and replaces the aforementioned weapons with a new lance weapon called the "Beast Killer" (which if implemented, should be way more expensive).

The end result of this bug / erroneous blanket coverage trivializes the importance of Snipers, Wind tomes (*when added*), and to a lesser extent, the ballista (*when added*). Which are already the delicate pegasi flier more than enough to worry about as-is.

**That being said, I suggest we take one of the following remedies:**

* Remove pegasi from these weapons' effective bonus
* Add the Beast Killer (*lance*) at a higher price than the Horseslayer, and do Option 1
* Merge the Horseslayer and Beast Killer's effective bonus but remove Pegasi from Longsword and Halberd which have also mentioned Cavalry units specifically in its description, but increase it's price considerably

-------

#### Reference:

http://fireemblem.wikia.com/wiki/Horseslayer

**Comment by SapphireTactician** [comment]
Just confirming that this is patched too before I can close it?

**Comment by eliatlarge** [comment]
closed by 0da79e907adc34fb
