### ISSUE TITLE
"Made in China" modifier doesn't start players with extra gold

### ISSUE THREAD

**Issue by SapphireTactician** [eliatlarge/FEMultiPlayer-V2#49]
Issue type: `problem`

#### Description:

See title. Players start with 48,000 gold even though the "Made in China" modifier clearly states, "All weapons have greatly reduced durability. Start with extra gold"

-------

#### Examples:

Mouse over "Made in China" modifier in FEServer, the description states, "All weapons have greatly reduced durability. Start with extra gold"

Players start 48,000 Gold regardless of if the modifier is active or not.

**Comment by eliatlarge** [comment]
Lol, I didn't even think people used the modifiers.

**Comment by SapphireTactician** [comment]
I've used a few already, it's nice to be able to just cut loose and have fun. :-D When Sarah and I use them, we mostly play with either Veterans and Treasury modifiers to place maximum emphasis on terrain and movement tactics (*which sadly I can't fully introduce her to because of #3 is not a thing yet*)
