### ISSUE TITLE
Miracle always activates if 1st / only hit would be fatal and unit was never damaged

### ISSUE THREAD

**Issue by SapphireTactician** [eliatlarge/FEMultiPlayer-V2#50]
Issue type: `problem`

#### Description:

Miracle currently has 100% activation rate if the following conditions are met:
* 1st / Only hit to unit is fatal
* Unit has never taken damage before

IMO, this defeats the point of Sages and Bishops who serve a very similar purpose but have inferior movement and can get one-shot at full health (*I feel these units could use a Def buff, especially Lucius*) in comparison by physical attacks due to not having it.

For better or worse, Miracle's activation rate is suppose to be Luck % if HP > 1.

-------

#### Reference:

http://fireemblem.wikia.com/wiki/Miracle

**Comment by eliatlarge** [comment]
I think we can just do the version from 6/7 that halves user's hp, if that's all right

**Comment by SapphireTactician** [comment]
>I think we can just do the version from 6/7 that halves user's hp, if that's all right

Miracle didn't exist in FE 6 - 8, so I guess you mean from 9 and 10 (*Path of Radiance and Radiant Dawn aka the Tellius Series*). Might be a fair tradeoff given the Luck % would make the activation rate pretty low, however I'm concerned that since this skill coupled with superior movement makes them currently overall better to Sages and Bishops, I think this should be balanced with either a Def buff for Sages / Bishops, or by giving Valkyries a Mag nerf. Opinions?

**Comment by eliatlarge** [comment]
mb, yeah 9-10. I think that halving rather than awakening-onwards' 1 hp would be a balanced alternative. I absolutely agree that mag should be nerfed for valkyries, ~~or maybe disable tome use~~

**Comment by rayrobdod** [comment]
https://github.com/eliatlarge/FEMultiPlayer-V2/blob/1.3/src/net/fe/fightStage/Miracle.java#L28

Miracle's activation rate is Luck%? What was your sample size?

**Comment by SapphireTactician** [comment]
Running two clients on my own computer, I pitted myself against a team of Lv 1 Valkyrie, Miracle activated without fail on all of them if they had full health and never battled that game.

**Comment by eliatlarge** [comment]
From what I see in the code, Here's what determines Miracle:

`return RNG.get() < user.get("Lck") && user.getHp() != 1;`

which translates to:

`successful if luck% and current hp is not 1.`

and for damage calculation:

```
if(d.getHp() - damage <= 0){
			return d.getHp() - 1;
		} else {
			return damage;
		}
```

meaning:

```
if this attack is lethal,
    deal damage equal to the HP - 1.
otherwise,
    deal normal damage.
```
English is a strange programming language. I do believe that the problem is that it uses the hp from the beginnning of the round, and if the unit has already been dealt damage, it will still deal damage equal to whatever the initial hp was minus 1.

**Comment by SapphireTactician** [comment]
>Best I can tell, you must have accidentally been running Divine Intervention. in that mode, 'Miracle' always triggers if hp is > 1, period. You might want to check on that, but I'll definitely look more into the code.

I can assure you I didn't enable any modifiers during this. It just triggers if the unit had full health, never participated in battle, and sustains a lethal hit on the first / only strike. FEMP hogging my CPU makes recording proof of this unfeasible but I'll get screenshots to show this later tonight as I can recreate this bug consistently.

**Comment by SapphireTactician** [comment]
![2016-04-21--212713_1600x900](https://cloud.githubusercontent.com/assets/18563664/14730033/fab95e7e-0810-11e6-889c-34dd8a513448.png)

First game of the night. Again, I can consistently trigger Miracle if the conditions I stated are fulfilled. I also don't have ANY modifiers running when this happens. Examine to code of both FEMP and FEServer to make sure that nothing is guaranteeing it for Valkyries.

**Comment by eliatlarge** [comment]
I tried with lvl 20 Eirika vs 3 Valkyries, and only 1 of them managed to proc miracle. You might want to try a fresh version of femp; perhaps the special miracle managed to *stick* on, somehow. or maybe you're the unluckiest (luckiest? main valkyries in the tourney) man alive.

**Comment by SapphireTactician** [comment]
> somehow. or maybe you're the unluckiest (luckiest? main valkyries in the tourney) man alive.

This, the Miracle streak finally came to an end late tonight after Sarah got cocky and brought multiple valkyries with her. They met their end at Sain's Halberd.

Closing as "Not A Bug / Works For Me". Meanwhile, maybe we should look at the RNG and see why it seems to roll a successful Miracle so often. Sorry for the inconvenience.

**Comment by eliatlarge** [comment]
True hit?

**Comment by SapphireTactician** [comment]
Not sure, it was a really bad string of luck for me apparently, sorry for the late reply. I just did the test running two clients on the same computer again with another valkyrie slaughter fest, all 3 on each team, and only one triggered Miracle. For whatever bizarre reason, it kept triggering beforehand without modifiers. I guess we'll never know what happened.
