### ISSUE TITLE
Add Fog of War and (FE5) Thracia 776 Fog of War modifiers to FEServer

### ISSUE THREAD

**Issue by ghost** [eliatlarge/FEMultiPlayer-V2#54]
Issue type: `feature request`
#### Description:

For the uninitiated, (_and for the sake of thorough documentation_) the Fog of War mechanic in Fire Emblem causes a fog to obscure the map from the player's vision. All units have a set field of vision (_this is often anywhere between 6 to 8 spaces for thief unit tiers such as Assassins who serve as the party's scout, and 3 spaces for everyone else_). These modifiers, needless to say, will lend a lot to tournaments as it prevents you from seeing what units and weapons your opponent has chosen (_Draft Mode would need to somehow implement double blind picks when Fog of War is active_)

- [x] **Classic Fog Of War modifier:**

In traditional Fog of War, the map is still visible (_although dimmer or hazy for tiles outside each unit's vision_), but enemy units are obscured if they're outside the player units' visual range. Ranged weapons also cannot target an enemy unit outside the player's collective field of vision (_i.e. the enemy unit must be visible in order to attack it_). If you bump into an enemy unit while moving through the fog, that unit who bumped into the enemy is immediately forced to Wait. As such, when selecting where to move, the movement path will allow spaces occupied by enemies to be considered as free / valid in order to not reveal their positions.

- [x] **Thracia 776 (_FE5_) Fog of War modifier:**

See also traditional Fog of War, EXCEPT that spaces outside each unit's visual range are completely blacked out. This adds a trial-and-error aspect to the battle. In addition to a unit being automatically forced to wait if they bump into an enemy unit while moving through the fog, I'd also suggest adding that If you bump into an obstacle (_such as a wall_) that the unit is forced to wait as well. As such, when selecting where to move, the movement path will allow spaces blacked out by the fog to be treated as free / valid for the purpose of not revealing their locations. In theory, this should be the easier of the two modifiers to add since we don't need any additional tilesets due to the tiles outside of visual range being blacked out.

In addition, FoW would greatly benefit from the following features:

- [x] We need an [exclamation mark indicator](https://fireemblemwiki.org/w/images/f/fe/Ss_fe07_fog_of_war_encounter.png) that alerts the player that they bumped into an enemy unit. With it missing, my testing partner was misled into thinking they misclicked or that a bug occurred instead of a legit game mechanic forcing their unit to wait. @eliatlarge Can I leave this to you since this would involve adding the needed graphics and such?

- [x] Add a Day / Night setting to make the fog easier to see.

- [x] PoR and later reduce the Thief's visual range to 5, FE 1 remakes reduce the Thief's visual range to +1 over that of the other units, meanwhile FE5 gives no sight bonus at all to thieves. I also like the current range too, but only for larger maps. Can you make this a server setting as well please?

- [x] Settings to control what spectators can see during FoW matches (*i.e. Red Only, Blue Only, Mutual Fields of Vision Only, Everything, Nothing*)

- [x] Add server setting to preventing "poking" / "brute forcing" the fog (*constantly moving and canceling to scout / cheat*). If the restriction is enabled, the user must commit to the location selected if they moved through fog.

---
#### References:
- http://fireemblem.wikia.com/wiki/Fog_of_War
- http://fireemblemwiki.org/Fog_of_war#Visibility

---
#### Examples:

**_Traditional:_**

![16-h13p10](https://cloud.githubusercontent.com/assets/18563664/16420281/b708526e-3d1e-11e6-922f-aea2c815ce37.png)

**_Thracia 776 (FE5):_**

![2-fe5_ 2 001](https://cloud.githubusercontent.com/assets/18563664/16420306/d500be5a-3d1e-11e6-898d-d2ad603929ae.png)

**Comment by SapphireTactician** [comment]
@wellme Great work on this so far with #148 . I found a bug which I'm going to open as a separate issue since it was merged. As for related requests / concerns, I'll just continue the conversation here.

* You know how the fog in the later FE games can be either hazy / washed out OR darker / dimmer (*such the night maps in Radiant Dawn*)? My test partner / gf sometimes has a difficult time seeing the actual fog, so I was thinking about having a day / night setting that just tweaks how the fog tints / filters the tiles.

* PoR and later reduce the Thief's visual range to 5, but I also like the current range too. Can make this a server setting as well if it's not too much trouble?

**Comment by rayrobdod** [comment]
Changing the fog from transparent white to transparent black results in the following; is this fog visible enough?

![fog-of-war but black instead of white](https://user-images.githubusercontent.com/11641215/36048355-edc30a5a-0dac-11e8-8826-06ff3561cc6b.png)

**Comment by SapphireTactician** [comment]
Yes, that's perfect. Idk if people care about how their fog looks but I'd like to see a client setting where they can choose between transparent white and transparent black if that's not too much of a hassle.
