### ISSUE TITLE
Graphical assets for fighting from a Fence are Missing!

### ISSUE THREAD

**Issue by SapphireTactician** [eliatlarge/FEMultiPlayer-V2#65]
Issue type: `problem`

#### Description:

When a unit positioned on a Fence is involved in an encounter, the resources needed are missing, triggering the failsafe textures named Whoops.  

-------

*P.S.: I'm loving the ProTactics mode! ^_^ Thank you!*

-------

#### Examples:

![2016-04-26--100948_1600x900](https://cloud.githubusercontent.com/assets/18563664/14821469/df2d3816-0b98-11e6-8ad1-fe347a04bfd2.png)
![2016-04-26--100915_1600x900](https://cloud.githubusercontent.com/assets/18563664/14821480/ead19efa-0b98-11e6-9694-91b6a5748c69.png)
![2016-04-26--101333_1600x900](https://cloud.githubusercontent.com/assets/18563664/14821482/ead23ff4-0b98-11e6-9774-2162cdb3de7f.png)
![2016-04-26--101405_1600x900](https://cloud.githubusercontent.com/assets/18563664/14821481/ead1e69e-0b98-11e6-808d-7c23fe60a03a.png)

**Comment by eliatlarge** [comment]
um... lol. thanks for catching that. I don't think anyone else would try fighting on every tile.

**Comment by SapphireTactician** [comment]
Welcome, that is my job after all with this project. :-) Instead of making a fence backdrop, I'd suggest having some sort of sky texture for the background and simply a transparent blank texture underneath the unit since Fences are only accessible to flying units.

**Comment by eliatlarge** [comment]
>at least you had enough foresight to institute a placeholder

that was chudooder, actually.

**Comment by SapphireTactician** [comment]
Ah, either way, I appreciate that kind of planning.

**Comment by eliatlarge** [comment]
closed by 5db0bb0

**Comment by SapphireTactician** [comment]
Are these in Master yet? Downloaded and built a zip and bug still persists.

**Comment by eliatlarge** [comment]
hopefully closed by I explicitly defined them. I really really hope it worked, I know it definitely did on my end.

**Comment by SapphireTactician** [comment]
Round 2, this time with terrain labeled as None, Fight!
