### ISSUE TITLE
[Visual] Map cursor overlaps Inventory during Trade

### ISSUE THREAD

**Issue by ghost** [eliatlarge/FEMultiPlayer-V2#69]
Issue type: `problem`
#### Description:

When trading, if the cursor is when the trading parties' inventories would be displayed, the cursor will remain on top.

---
#### Examples:

![2016-04-26--111501_1600x900](https://cloud.githubusercontent.com/assets/18563664/14837934/8ca827f2-0bea-11e6-8839-bdfd053c3d1a.png)

**Comment by SapphireTactician** [comment]
Closing as fixed as per #139  

Good job @wellme
