### ISSUE TITLE
Cursor starting position isn't the location of the player's Lord during Player Phase

### ISSUE THREAD

**Issue by SapphireTactician** [eliatlarge/FEMultiPlayer-V2#74]
Issue type: `problem` `feature request` (both)

#### Description:

The default behavior of FE games is to return / position the cursor over the player's Lord at the beginning of each Player Phase (*because Lords can fall without instantly losing the match in FEMP, except during Seize the Throne, as a failsafe, in the event that the player loses their Lord, it should then position the cursor over the highest level unit*).

Instead, the cursor is usually somewhere near the top-left corner of the map. Forcing the player to either locate their team manually, or use the C button to cycle to one of their units.

-------

#### Examples:

![2016-04-26--190044_1600x900](https://cloud.githubusercontent.com/assets/18563664/14841528/906bd402-0c0c-11e6-88f3-46ccd65482c0.png)

**Comment by rayrobdod** [comment]
Maybe for the start of the match this should occur. But FE also has the option of the cursor starting the turn with the cursor where it was left at the end of the previous turn, and FEMP lets players control their cursor during the opponent's turn. The cursor jumping back to the lord at a frankly unpredictable time would interfere should a player be looking up information during the opponent's turn.

**Comment by SapphireTactician** [comment]
True, can this option be added to app.config?

**Comment by SapphireTactician** [comment]
Closing as `Fixed` as per #107
