### ISSUE TITLE
Aid stat

### ISSUE THREAD

**Issue by SapphireTactician** [eliatlarge/FEMultiPlayer-V2#75]
Issue type: `feature request`

#### Description:

The Aid stat is a stat all units should have because it simplifies commands like Rescue, Give, and Take. As long as the unit performing the Rescue / Take command's Aid is greater than or equal to the Con of the person being rescued / taken (*referred hereafter as the "Traveler" as per FE naming convention*), they can Rescue / Take that unit. Likewise, when using the Give command, one can pass the Traveler to another unit so long as the Traveler's Con is less than or equal to the target's Aid.

You can determine any character's Aid by using 1 of these 3 formulas depending on if their on foot, male rider / flier, or female rider / flier:

* For any unit on foot: `Aid = Con - 1`
* For males mounted on horse, pegasi, or wyvern: `Aid = 25 - Con`
* For females mounted on horse, pegasi, or wyvern: `Aid = 20 - Con`

This makes addressing #41 MUCH easier without tiers or anything confusingly complex and unnecessary.

-------

#### References:

http://fireemblemwiki.org/wiki/Aid
http://fireemblem.wikia.com/wiki/Aid

**Comment by SapphireTactician** [comment]
It's come to my attention that Male Paladins get a +2 Aid as part of their Promotional Gains to offset how their Con gains would adversely affect their rescuing ability (*and would otherwise making rescuing a unit like Oswin impossible*). In other words:

* For Male Paladins: `Aid = (25 + 2) - Con`

Other formulas remain the same.

**Comment by eliatlarge** [comment]
I feel that doing it with all male paladins would give us more uniformity.

**Comment by SapphireTactician** [comment]
Works for me, as long at least some of the male paladins get the +2 Aid Promotion Gain like they did in the GBA games, otherwise only Pegasi will have enough Aid to rescue units with 15 and 16 Con like Generals, Bartre, and Hector.
