### ISSUE TITLE
[Visual] Terrain labeled as "None" triggers failsafe "Whoops" textures during encounters

### ISSUE THREAD

**Issue by ghost** [eliatlarge/FEMultiPlayer-V2#78]
Issue type: `problem`
#### Description:

In FEMP, there are pieces of terrain, namely doors / gates, and parts of buildings and villages accessible only to flyers, that are labeled as "None". When an encounter involves a unit such as a Pegasi positioned on such a space, because the terrain was never named, assets were most likely never assigned to them - resulting in the same effect as #65  

These misc. pieces of terrain need to be assigned a name, perhaps "Structure", "Building", or even "Misc.", and given an appropriate backdrop such as a clear sky when considering it's only accessible to flying units.

---
#### Examples:

The first two screenshots demonstrate various terrain with the label of None. The last screenshot shows the end result.

![2016-04-28--093943_1600x900](https://cloud.githubusercontent.com/assets/18563664/14888319/bc73050e-0d27-11e6-85e5-04f26b767012.png)
![2016-04-28--093634_1600x900](https://cloud.githubusercontent.com/assets/18563664/14888323/c231b9b8-0d27-11e6-9374-385d00f9956a.png)

![2016-04-28--092558_1600x900](https://cloud.githubusercontent.com/assets/18563664/14888379/fbe04742-0d27-11e6-9200-57f63f70248c.png)

_**Once again, Florina opens the gates to another dimension.  Let's end her reign of graphical terror, please and thank you.**_

_On a happier note, we can clearly see Eclipse working again, however it seems to cause a bit of slowdown on this PC, at least when running two clients and the server altogether._

**Comment by eliatlarge** [comment]
wtf are pegasi doing on none? running 2 clients and the server is the equivalent of running 3 clients.

**Comment by SapphireTactician** [comment]
>wtf are pegasi doing on none?

Well, in the GBA games, those were valid spaces for pegasi to land. FE7 did label them "--" which is pretty much the same as saying "None"

**Comment by eliatlarge** [comment]
oh, huh. I guess I'll have to do something about that. are there any other none spaces a pegasi can enter? also, I'd like to see the log so I can know what its asking for.

**Comment by SapphireTactician** [comment]
In FEMP? They can also roost on top of the tan color villages and the building that resembles an Armory as well as the gate door along the center of the northern wall in the Town map. As for a log, I'll see what my terminal outputs for encounters on "None" terrain.

**Comment by SapphireTactician** [comment]
>I'd like to see the log so I can know what its asking for.

Wish granted. :-) Terminal output is from the beginning of the Enemy Phase, up to and including when Ewan attacks Florina (*whose positioned on a piece of "None" terrain*), triggering the failsafe textures:

    Loaded res/gui/enemy_phase.png
    Loaded res/gui/red_flash.png
    Loaded res/battle_anim/sorcerer_magic_attack.png
    Loaded res/battle_anim/sorcerer_magic_critical.png
    Loaded res/battle_anim/sorcerer_magic_dodge.png
    Loaded res/battle_anim/falconknight_lance_attack.png
    Loaded res/battle_anim/falconknight_lance_critical.png
    Loaded res/battle_anim/falconknight_lance_dodge.png
    Loaded res/gui/gui_tickFilled.png
    Loaded res/gui/gui_tickEmpty.png
    Loaded res/battle_anim/static/platform_plain_far.png
    Warn: platform_none_far not explicitly defined
    Loaded res/whoops.png
    Loaded res/gui/gui_battleStats.png
    Warn: none_bg not explicitly defined
    Loaded res/whoops.png
    PRELoaded res/battle_anim/magic_effect_null.png
    PRELoaded res/battle_anim/magic_effect_null.png
    PRELoaded res/battle_anim/hit_effect_eclipse.png
    Loaded res/battle_anim/miss.png
    Ewan HP:39 | Florina HP:36
    
    Loaded res/gui/player_phase.png
    Loaded res/gui/blue_flash.png

**Comment by SapphireTactician** [comment]
>server is just a headless client, really.

Ah, that explains why they're similar in file size and their jars contain even music and graphics. Would the server application run more efficiently if was made to be truly standalone?

**Comment by eliatlarge** [comment]
I honestly don't know. i do know that it loads some of the resources, but idk if it would change the efficiency. it's possible.

**Comment by SapphireTactician** [comment]
Closing as `Fixed` as per #139  

@wellme I wish we had an open sky BG for when both are on `None` as that's generally how the official games handled it iirc.
