### ISSUE TITLE
"Vegas" Modifier and / or Gamble skill are not calculating Hit and Crit rates correctly

### ISSUE THREAD

**Issue by SapphireTactician** [eliatlarge/FEMultiPlayer-V2#83]
Issue type: `problem`

#### Description:

The "Vegas" modifier (*All units have "Gamble" skill - halved accuracy but double crit rate*) is clearly doing neither. Honestly I have no idea what kind of math it's employing but it's certainly not halving accuracy and doubling crit rate when comparing the Battle Forecast's reflected with-gamble changes (*first screenshot*), to the encounter's original pre-gamble values (*second screenshot*).

If the rates were correctly calculated, the Hit in the first image would be half of the Hit in the second image. Likewise, the Crit in the first image would be double the Crit in the second.

This is not just a visual problem, no one's hitting, and having the forecast window reflecting the rates with gamble explains why, most character's can't even top 10% hit despite it originally being 70+.

-------

#### Examples:

The first screenshot shows the Battle Forecast Window. The Battle Forecast for this mode has been adjusted to reflect the changes Gamble makes in advance due to all units having Gamble in this mode. (*This is the intended and desired behavior, nothing wrong here other than the hit being calculated so incorrectly that it's near impossible for units to hit each other*)

![2016-04-30--203219_1600x900](https://cloud.githubusercontent.com/assets/18563664/14939781/286791f0-0f24-11e6-9dbe-abe9c8eb87f5.png)

This second screenshot is of the actual encounter. This shows the what the probabilities would've been under ordinary circumstances. Notice how the Hit in the first picture is not half of the Hit in the below image. Likewise, notice how the Crit rate above is not double the Crit rate of the image below. Accuracy is being reduced by way more than half, and Crit is becoming more than doubled.

![2016-04-30--203229_1600x900](https://cloud.githubusercontent.com/assets/18563664/14939796/8dba179e-0f24-11e6-8c54-02af4ed74a27.png)

**Comment by SapphireTactician** [comment]
Maybe I'm just having a repeat of the Miracle incident but this is a log of roughly 10 turns of fighting where only a small handful of attacks ever landed, even times when they had the highest possible accuracy of 50%. On average though, the accuracy fell in the range of 30%.

[server_log8680236.log](https://github.com/eliatlarge/FEMultiPlayer-V2/files/246114/server_log8680236.txt)

*P.S.: Any way we can make the number appended to the log a timestamp, as in server_log20160502-195030 instead of just nonsensical numbers that make me have to sort by modified date?*

**Comment by eliatlarge** [comment]
Its by msec to prevent dupes, but that's never been a problem for me, though I can see how it can be on Linux. I'll try to remember, but if its an issue, you may want to put it in the issue tracker so i'll be able to see it better.

**Comment by SapphireTactician** [comment]
I don't have anything special to test RNG with but when you look at that log, that's a lot of misses, with 50% accuracy after Gamble, Edward missed all 5 hits with Astra, then missed his double. I could just be having bad luck like with Miracle but I still wonder if there's bad or somehow biased rolls.
