### ISSUE TITLE
Unnerf Staves / Make Staves use correct healing formula

### ISSUE THREAD

**Issue by SapphireTactician** [eliatlarge/FEMultiPlayer-V2#85]
Issue type: `problem`

#### Description:

As per [here](https://www.reddit.com/r/FEMP/comments/4hm2mm/why_does_mend_larachel_only_heal_17_not_34/), [here](https://www.reddit.com/r/FEMP/comments/4fi6c5/bug_fix_weapon_misc_suggestions/), [here](https://www.reddit.com/r/FEMP/comments/4fi6c5/bug_fix_weapon_misc_suggestions/d29ic88), [and here](https://www.reddit.com/r/FEMP/comments/4hm2mm/why_does_mend_larachel_only_heal_17_not_34/d2rkfa8) it seems that the sub in consensus that staves should be using their correct healing formulas of `10 + Mag` for Heal, `20 + Mag` for Mend, and `10 + Mag` for Physic (*range on Physic btw is (`1 ~ Mag/2`*).

As per @eliatlarge 's comment on https://www.reddit.com/r/FEMP/comments/4hm2mm/why_does_mend_larachel_only_heal_17_not_34/ I am opening this as an issue.

-------

#### References:

http://fireemblem.wikia.com/wiki/Heal
http://fireemblem.wikia.com/wiki/Mend
http://fireemblem.wikia.com/wiki/Physic

**Comment by eliatlarge** [comment]
It appears that the healing value was mag/2 + healvalue/2, for some reason.

**Comment by rayrobdod** [comment]
8a4854c86e3e91821644f4e8cbe7f7d44c7d87d7

**Comment by SapphireTactician** [comment]
@rayrobdod Does this also fix Physic's range to be from 1 to Mag/2, so it won't be considered OP to some?

**Comment by rayrobdod** [comment]
Was that also a part of this issue? The commit does not appear to change Physic's range, but the relation of the first half probably justifies linking this issue and that commit.

**Comment by eliatlarge** [comment]
I didn't know that was requested. I'll look into it.

**Comment by SapphireTactician** [comment]
Range correction wasn't requested yet, but probably will be given Physic's potential. Can always ask the sub to make sure but I think they'll be on board with it so that it doesn't overshadow Mend and Recover too easily.

**Comment by eliatlarge** [comment]
well it happened at least, so sucks to suck.

**Comment by SapphireTactician** [comment]
>I can see this messing with 1 level healers, since they'll have significantly debuffed range.

Good, if they want to make use of Physic, they need to proper invest in their healer. That was a cheap strat.

**Comment by eliatlarge** [comment]
now I need to make it *actually* work

I really need to get back to testing before committing

**Comment by SapphireTactician** [comment]
Sorry, I would've done that for you but I've been busy testing out #87

**Comment by eliatlarge** [comment]
oh i wasn't actually testing it, I thought you were

**Comment by eliatlarge** [comment]
ok well it works now so lets pretend that nothing happened, and ray can keep pretending like I'm a good coder
