### ISSUE TITLE
Log Filenames Aren't Useful / Chronological

### ISSUE THREAD

**Issue by SapphireTactician** [eliatlarge/FEMultiPlayer-V2#88]
Issue type: `problem`

#### Description:

In their current state, especially when their quantity becomes unwieldy, it becomes time consuming and frustrating to find all the logs related to a particular incident because the number at the end of each file isn't human-readable. To complicate matters, whatever measurement these filenames use don't appear to factor in date, only time, meaning that when sorted by name, they're out of order if the logs harvested are from multiple days.

I recommend and insist (*for our sanity*) that the number appended to each log file be a date and military (*24 hour*) timestamp. In the event multiple logs of the same name (*down to the second*) spawn, it should append an underscore to that number with another number that denotes the order of creation (*i.e. `error_log_client_2016-05-15_161205_xx.log`*).  
  
I know we got much larger priorities after last night but this will really help streamline things for me, especially when collaborating and harvesting logs from other testers.

-------

#### Examples:

`error_log_server_2016-05-15_004746.log` instead of `error_log_server87666573.log`

`server_log_2016-05-01_160713.log` instead of `server_log33233303.log`

**Comment by eliatlarge** [comment]
closed by b86dd17
