### ISSUE TITLE
[Fatal] FEServer (v1.4.0) : Null Pointer Exception

### ISSUE THREAD

**Issue by SapphireTactician** [eliatlarge/FEMultiPlayer-V2#90]
Issue type: `problem`

#### Description:

Another FEServer crash. I wasn't personally in this match, as it was between Sarah and NeoFire99. To relieve CPU stress since my match was over, I was running only FEServer when the crash occurred so I could watch the match on Twitch when I bore witness to this:

![2016-05-14--222927_1600x900](https://cloud.githubusercontent.com/assets/18563664/15336673/af774d74-1c45-11e6-82d7-97b39b691d98.png)

Pay close attention to Erk's inventory icons... And with that glorious vision, Duffle canceled the tournament and ended stream. I am at a complete loss for words with the above, but I'm going to refrain from filing that as a report since @eliatlarge said something about an experiment with FEServer and removing asset files from it which may or may not have been the cause of the visual aspect of this madness. Otherwise something went seriously wrong with #84  

-------

#### Logs (*in order of log file creation*):

From `error_log_server_listener79167435.log` @ Sat, May 14, 10:26:07 PM EDT

    java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:209)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.net.SocketInputStream.read(SocketInputStream.java:223)
        at java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2303)
        at java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:2596)
        at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2606)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1319)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
        at net.fe.network.ServerListener.run(ServerListener.java:80)

From `error_log_server79237949.log` @ Sat, May 14, 10:27:17 PM EDT

    java.lang.NullPointerException
        at net.fe.Session.removePlayer(Session.java:81)
        at net.fe.overworldStage.OverworldStage.beginStep(OverworldStage.java:292)
        at net.fe.network.FEServer.loop(FEServer.java:347)
        at net.fe.network.FEServer$4$2.run(FEServer.java:263)

##### Attachments:

Error logs and match log.

[FEServerNullPointer_Fatal_Logs.zip](https://github.com/eliatlarge/FEMultiPlayer-V2/files/269308/FEServerNullPointer_Fatal_Logs.zip)

**Comment by eliatlarge** [comment]
It looks like another player on the other side crashed. can you ask him for his logs?

**Comment by SapphireTactician** [comment]
I just realized in the screenshot that Erk's range for Physic is wrong. I have a feeling one of the NeoFire99 was using v1.3 still unless there's a regression v1.4.

Sarah doesn't have any error logs according to her but I'll double check. I don't know the other player, someone else from the sub invited 'em via advertising on /r/fireemblem

We'll have to make due with what we have, I'm afraid.

**Comment by eliatlarge** [comment]
That desync thing would make absolute sense if he were using a different ver, coupled with the shifted items (whose id's we changed in 1.4).

**Comment by SapphireTactician** [comment]
Desync is #89 between me and Pwntagonist. This was just a null pointer exception crash with funky icons.

**Comment by SapphireTactician** [comment]
Sarah's `error_log_client79219665.log` @ Sat, May 14, 10:26:59 PM EDT

    java.lang.NullPointerException
        at net.fe.Session.removePlayer(Session.java:81)
        at net.fe.overworldStage.OverworldStage.beginStep(OverworldStage.java:292)
        at net.fe.overworldStage.ClientOverworldStage.beginStep(ClientOverworldStage.java:249)
        at net.fe.FEMultiplayer.loop(FEMultiplayer.java:342)
        at net.fe.FEMultiplayer.main(FEMultiplayer.java:101)

**Comment by eliatlarge** [comment]
has this issue continued with fix1?

**Comment by SapphireTactician** [comment]
Given neither client was on my end, I only had FEServer open at the time, I have no idea where to even begin looking to try to reproduce this bug. I know Sarah had v1.4.0 (*latest at the time*) as for the others, I don't know, and I have no means of even contacting the other player. You'll have to contact **DuffleGamer** (*who I think invited him via FE, or was it BChezza, idr*) and have him talk to **NeoFire99** to figure that out for you as either he or Duffle might've been using v1.3. That's all I can tell you.

**Comment by eliatlarge** [comment]
I'm checking, but neo is offline rn. I'll update you by tomorrow, hopefully.

**Comment by rayrobdod** [comment]
> But how can that be, this is from Duffle's broadcast, so wouldn't Duffle if he was using v1.4.0 see the correct range even if the opponent had the wrong version? Now I'm REALLY confused

When teams are serialized, it doesn't store a reference to an item (like say just an item's name that the server can then use a lookup table to find), the entire item is stored. So, the 1.3 client sends a Physic with range 1-15, the server receives a Physic with range 1-15 and then the server fails to question the odd Physic (#94 Y/N?).

**Comment by SapphireTactician** [comment]
I didn't even pen #94 at the time of writing because stupid me assumed such essential safeguards would've already been in place, and that it was more #61 (*it's very dangerous for the game to assume everyone is using the same version, or an unmodded version*) which would be an extension of #94 the more that I think about it.

Makes me curious if a spectator using a mismatched version could cause havoc too. @rayrobdod What's the prognosis of stamping out at least #94 ? And possible also #61 (*though addressing #61 would prevent players from injecting their own music and such until #45 is implemented*)

**Comment by rayrobdod** [comment]
#61 was what I was actually looking for, yes.

**Comment by rayrobdod** [comment]
>>When teams are serialized, it doesn't store a reference to an item (like say just an item's name that the server can then use a lookup table to find), the entire item is stored.

> Which in turn makes it rely too heavily on the hope that everyone is running not just an identical version number, but identical unedited versions

When a battle occurs, the initiating client asks the server what happened, the server pulls numbers from an RNG to determine the results, then the server tells the clients what the results were. The alternative would be for the server to, at the start of a game, tell the clients a RNG seed, and then for each battle the clients can pull numbers from the RNG (pseudorandom, so the same numbers on all clients) and determine the results themselves. The latter is theoretically possible, but (in addition to being incredibly fragile and exhibiting poor information hiding) relies on the clients being identical far more than the former.

In the same way, I am fairly certain that the server saying "Here are all the details about a unit" is far more tolerant of non-identical clients than the server saying "Here is the name of a unit; figure out everything else yourself".

> `weapons.txt` doesn't say `1-Mag/2`

CombatTriggers aren't in that document either. And there are more of those (5 if statements covering 13-I-think weapons).

**Comment by SapphireTactician** [comment]
>In the same way, I am fairly certain that the server saying "Here are all the details about a unit" is far more tolerant of non-identical clients than the server saying "Here is the name of a unit; figure out everything else yourself".

So you're saying that once players join the server, the server should override all clients `weapons.txt` and `stats.txt` to allow more version flexibility when the version difference is merely balance patches and not new features? While this would work when the version difference is solely balance patches, this idea probably won't prevent things from catching fire if a newer client makes uses of a feature that don't exist on the earlier one such as shoving. We've learned through experience that we can't expect all players to be on the same page as the host.

**Comment by SapphireTactician** [comment]
Closing as `Fixed` as per #102 

Great job! @rayrobdod
