### ISSUE TITLE
[Fatal] FEServer (v1.4.X) crashes if weapon breaks while possessing more than 1 usable weapon

### ISSUE THREAD

**Issue by SapphireTactician** [eliatlarge/FEMultiPlayer-V2#95]
Issue type: `problem`

#### Description:

~~The 3rd and final bug observed specifically during v1.4.0.~~ This was during a friendly between **Pwntagonist** and I. It occured during late endgame was I ending my turn. According to the logs, the crash seems to have occurred the moment **Pwntagonist** summoned yet another Phantom, producing the following error:

    java.lang.ClassCastException: net.fe.overworldStage.OverworldStage cannot be cast to net.fe.overworldStage.ClientOverworldStage
        at net.fe.unit.Unit.equip(Unit.java:570)
        at net.fe.unit.Unit.reEquip(Unit.java:700)
        at net.fe.unit.Unit.use(Unit.java:749)
        at net.fe.unit.Unit.use(Unit.java:714)
        at net.fe.overworldStage.OverworldStage.processCommands(OverworldStage.java:429)
        at net.fe.overworldStage.OverworldStage.beginStep(OverworldStage.java:263)
        at net.fe.network.FEServer.loop(FEServer.java:347)
        at net.fe.network.FEServer$4$2.run(FEServer.java:263)

~~I honestly have no idea why that particular summon was the straw that broke the server's back.~~

![2016-05-15--005028_1600x900](https://cloud.githubusercontent.com/assets/18563664/15441348/606c6ccc-1ea8-11e6-8ec4-cab99dd42928.png)

~~It's interesting to note that while the log shows a Phantom was summoned, it never appeared.~~ The crash occurs whenever a unit who has a spare weapon breaks their weapon.

-------

#### Logs:

[v140_FEServerPhantomCrash_logs.zip](https://github.com/eliatlarge/FEMultiPlayer-V2/files/275385/v140_FEServerPhantomCrash_logs.zip)

**Comment by rayrobdod** [comment]
`reEquip`… I imagine a Rose tome broke? Yeah, Log indicates that that was Canas's fourth summon, so a Rise tome broke.

So, new experiment: Ewan gets 4 Eclipse tomes. He attacks Eliwood once; nothing breaks. He attacks Eliwood a second time, and viola! [v140_EclipseCrash_logs.zip](https://github.com/eliatlarge/FEMultiPlayer-V2/files/275766/v140_EclipseCrash_logs.zip) When an Eclipse ran out of durability, the server crashed.

When an item runs out of durability, a routine is called which includes an "I, as a client, am telling the server that a player has performed an action" part, which the server should not be doing.

**Comment by SapphireTactician** [comment]
Can confirm in v1.4.1 as well with any weapon. It seems that so long as the unit has more than 1 usable weapon (*they don't have to be identical either*), the game will crash upon breaking a weapon. What's odd is that I never encountered this bug in earlier builds such as v1.3.

Updating title to reflect this bug applies to v1.4.1 as well.

**Comment by SapphireTactician** [comment]
Closing as `Fixed` as per #102 

Great job! @rayrobdod
